tasks:
  - init: pip install -e .[dev]

github:
  prebuilds:
    master: true
    branches: false
    pullRequests: true
    pullRequestsFromForks: true
    addComment: false
    addBadge: false
    addLabel: false

vscode:
  extensions:
    - christian-kohler.path-intellisense
    - cschleiden.vscode-github-actions
    - davidanson.vscode-markdownlint
    - eamodio.gitlens
    - editorconfig.editorconfig
    - esbenp.prettier-vscode
    - github.vscode-pull-request-github
    - ms-python.flake8
    - ms-python.isort
    - ms-python.pylint
    - ms-python.python
    - ms-python.vscode-pylance
    - ms-vsliveshare.vsliveshare
    - redhat.vscode-yaml
    - ryanluker.vscode-coverage-gutters
    - stkb.rewrap
    - streetsidesoftware.code-spell-checker
    - tamasfe.even-better-toml
    - travisillig.vscode-json-stable-stringify
    - tyriar.sort-lines
    - yzhang.markdown-all-in-one
