- id: check-dev-files
  name: Check developer config files in the repository
  entry: check-dev-files
  language: python
  always_run: true
  pass_filenames: false

- id: fix-nbformat-version
  name: Set nbformat minor version to 4 and remove cell IDs
  entry: fix-nbformat-version
  language: python
  types:
    - jupyter

- id: format-setup-cfg
  name: Format setup.cfg
  entry: format-setup-cfg
  language: python
  files: ^setup.cfg$

- id: pin-nb-requirements
  name: Check whether notebook contains a pip install line
  description: >
    Specify which packages to install specifically in order to run this
    notebook.
  entry: pin-nb-requirements
  language: python
  types:
    - jupyter

- id: set-nb-cells
  name: Add or update default cells in a Jupyter notebook
  description: >
    Add or replace certain default cells in a Jupyter notebook.
  entry: set-nb-cells
  exclude: >
    (?x)^(
      docs/adr/.*
    )$
  language: python
  types:
    - jupyter
