- id: check-dev-files
  name: Check developer config files in the repository
  entry: check-dev-files
  language: python
  always_run: true
  pass_filenames: false

- id: colab-toc-visible
  name: Show the TOC sidebar in Google Colab by default
  entry: colab-toc-visible
  language: python
  types:
    - jupyter

- id: fix-nbformat-version
  name: Set nbformat minor version to 4 and remove cell IDs
  entry: fix-nbformat-version
  language: python
  types:
    - jupyter

- id: remove-empty-tags
  name: Remove empty tags metadata field from Jupyter notebooks
  description: >
    Remove the tags metadata field from Jupyter notebooks if there are no tags
  entry: remove-empty-tags
  language: python
  types:
    - jupyter

- id: set-nb-cells
  name: Add or update default cells in a Jupyter notebook
  description: >
    Add or replace certain default cells in a Jupyter notebook.
  entry: set-nb-cells
  exclude: >
    (?x)^(
      docs/adr/.*
    )$
  language: python
  types:
    - jupyter

- id: set-nb-display-name
  name: Revert display name of the notebook kernel
  description: >
    Remove the tags metadata field from Jupyter notebooks if there are no tags
  entry: set-nb-display-name
  language: python
  types:
    - jupyter
