from __future__ import annotations

from textwrap import dedent
from typing import TYPE_CHECKING

from compwa_policy.utilities import prek

if TYPE_CHECKING:
    from collections.abc import Callable
    from pathlib import Path

    import pytest

_PRECOMMIT_SHIM = dedent("""
    #!/usr/bin/env bash
    # File generated by pre-commit: https://pre-commit.com
    ARGS=(hook-impl --config=.pre-commit-config.yaml --hook-type=pre-commit)
    """).lstrip()


def _install_shim(repo: Path, hook_type: str, content: str) -> None:
    hooks_dir = repo / ".git" / "hooks"
    hooks_dir.mkdir(parents=True, exist_ok=True)
    (hooks_dir / hook_type).write_text(content)


def describe_find_precommit_git_shims():
    def finds_nothing_outside_a_repository(
        tmp_path: Path, monkeypatch: pytest.MonkeyPatch
    ):
        monkeypatch.chdir(tmp_path)
        monkeypatch.setenv("GIT_CEILING_DIRECTORIES", str(tmp_path.parent))
        assert prek.find_precommit_git_shims() == []

    def finds_nothing_without_installed_hooks(
        tmp_path: Path,
        monkeypatch: pytest.MonkeyPatch,
        git_init: Callable[[Path], None],
    ):
        git_init(tmp_path)
        monkeypatch.chdir(tmp_path)
        assert prek.find_precommit_git_shims() == []

    def ignores_hooks_that_prek_or_a_user_wrote(
        tmp_path: Path,
        monkeypatch: pytest.MonkeyPatch,
        git_init: Callable[[Path], None],
    ):
        git_init(tmp_path)
        monkeypatch.chdir(tmp_path)
        _install_shim(tmp_path, "pre-commit", "#!/bin/sh\nexec prek hook-impl\n")
        assert prek.find_precommit_git_shims() == []

    def lists_shims_generated_by_pre_commit(
        tmp_path: Path,
        monkeypatch: pytest.MonkeyPatch,
        git_init: Callable[[Path], None],
    ):
        git_init(tmp_path)
        monkeypatch.chdir(tmp_path)
        _install_shim(tmp_path, "pre-commit", _PRECOMMIT_SHIM)
        _install_shim(tmp_path, "pre-push", _PRECOMMIT_SHIM)
        assert prek.find_precommit_git_shims() == ["pre-commit", "pre-push"]


def describe_install_prek_git_shims():
    def does_nothing_without_stale_shims(capsys: pytest.CaptureFixture):
        prek.install_prek_git_shims([])
        assert not capsys.readouterr().out

    def reports_the_command_if_prek_is_not_installed(
        monkeypatch: pytest.MonkeyPatch, capsys: pytest.CaptureFixture
    ):
        monkeypatch.setattr(prek.shutil, "which", lambda _: None)
        prek.install_prek_git_shims(["pre-commit", "pre-push"])
        out = capsys.readouterr().out
        assert "prek is not installed" in out
        assert "--hook-type pre-commit --hook-type pre-push" in " ".join(out.split())

    def runs_prek_install_with_the_stale_hook_types(monkeypatch: pytest.MonkeyPatch):
        commands: list[list[str]] = []
        monkeypatch.setattr(prek.shutil, "which", lambda _: "/usr/bin/prek")
        monkeypatch.setattr(
            prek.subprocess, "run", lambda cmd, **_: commands.append(cmd)
        )
        prek.install_prek_git_shims(["pre-commit"])
        assert commands == [
            ["/usr/bin/prek", "install", "--force", "--hook-type", "pre-commit"]
        ]
