"""Helpers for switching a repository from pre-commit to `prek <https://prek.j178.dev>`_.

`prek <https://prek.j178.dev>`_ is a drop-in replacement for `pre-commit
<https://pre-commit.com>`_: it reads the same :file:`.pre-commit-config.yaml` file, so
switching only affects how the hooks are *run*. The Git hook shims under
:file:`.git/hooks` are the one thing that cannot be updated by the ``check-dev-files``
hook itself: they are not tracked by Git and each developer installs them locally. The
``policy migrate`` command therefore detects shims that were generated by ``pre-commit
install`` and replaces them with ``prek`` shims.
"""

from __future__ import annotations

import shutil
import subprocess  # ruff: ignore[suspicious-subprocess-import]
from pathlib import Path

import rich

__PRECOMMIT_SHIM_MARKER = "File generated by pre-commit"
"""Header that :code:`pre-commit install` writes into each Git hook shim."""

HOOK_TYPES = (
    "commit-msg",
    "post-checkout",
    "post-commit",
    "post-merge",
    "post-rewrite",
    "pre-commit",
    "pre-merge-commit",
    "pre-push",
    "pre-rebase",
    "prepare-commit-msg",
)
"""Git hook types that both pre-commit and prek can install a shim for."""


def find_precommit_git_shims() -> list[str]:
    """List the Git hook types whose shim was installed by ``pre-commit install``."""
    hooks_dir = __get_git_hooks_dir()
    if hooks_dir is None:
        return []
    return [
        hook_type
        for hook_type in HOOK_TYPES
        if __is_precommit_shim(hooks_dir / hook_type)
    ]


def install_prek_git_shims(hook_types: list[str]) -> None:
    """Overwrite the given Git hook shims with ``prek`` shims.

    If ``prek`` is not installed, the existing shims are left untouched and the command
    to run after installing ``prek`` is printed instead.
    """
    if not hook_types:
        return
    arguments = ["install", "--force", *__hook_type_flags(hook_types)]
    executable = shutil.which("prek")
    if executable is None:
        command = " ".join(["prek", *arguments])
        rich.print(
            "[yellow]prek is not installed, so the pre-commit Git hooks were left in"
            " place. Install it with[/yellow] uv tool install prek [yellow]and"
            f" run[/yellow] {command}"
        )
        return
    subprocess.run([executable, *arguments], check=False)  # ruff: ignore[subprocess-without-shell-equals-true]


def __hook_type_flags(hook_types: list[str]) -> list[str]:
    """Render hook types as ``prek install`` flags.

    >>> __hook_type_flags(["pre-commit", "pre-push"])
    ['--hook-type', 'pre-commit', '--hook-type', 'pre-push']
    """
    return [arg for hook_type in hook_types for arg in ("--hook-type", hook_type)]


def __get_git_hooks_dir() -> Path | None:
    try:
        output = subprocess.check_output(
            ["git", "rev-parse", "--git-path", "hooks"],  # ruff: ignore[start-process-with-partial-path]
            stderr=subprocess.DEVNULL,
        )
    except (OSError, subprocess.CalledProcessError):
        return None
    hooks_dir = Path(output.decode("utf-8").strip())
    if not hooks_dir.is_dir():
        return None
    return hooks_dir


def __is_precommit_shim(path: Path) -> bool:
    if not path.is_file():
        return False
    try:
        content = path.read_text(errors="ignore")
    except OSError:
        return False
    return __PRECOMMIT_SHIM_MARKER in content
