tasks:
  - init: pyenv local 3.9
  - init: pip install -e .[dev]

github:
  prebuilds:
    master: true
    branches: false
    pullRequests: true
    pullRequestsFromForks: true
    addComment: false
    addBadge: false
    addLabel: false

vscode:
  extensions:
    - charliermarsh.ruff
