name: pre-commit

on:
  push:
    branches:
      - main
      - epic/*
      - "[0-9]+.[0-9]+.x"
  pull_request:
    branches:
      - main
      - epic/*
      - "[0-9]+.[0-9]+.x"
  workflow_dispatch:

jobs:
  style:
    name: Style checks
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          key: |
            ${{ github.workflow }}-${{ github.job }}-${{ runner.os }}-${{ hashFiles('.constraints/py3.*.txt', '.pre-commit-config.yaml') }}
          path: |
            .mypy_cache/
            ~/.cache/pip/
            ~/.cache/pre-commit/
      - uses: actions/setup-python@v4
        with:
          python-version: "3.8"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .[sty]
      - name: Run non-local pre-commit hooks
        run: |
          {{ WILL BE FILLED OUT BY PRE-COMMIT }}
      - name: Run pre-commit hooks that don't work on pre-commit.ci
        run: |
          {{ WILL BE FILLED OUT BY PRE-COMMIT }}
