name: CD

on:
  release:
    types:
      - prereleased
      - released

jobs:
  milestone:
    if: startsWith(github.ref, 'refs/tags')
    uses: ComPWA/actions/.github/workflows/close-milestone.yml@v1
  push:
    if: startsWith(github.ref, 'refs/tags') && !github.event.release.prerelease
    secrets: inherit
    uses: ComPWA/actions/.github/workflows/push-to-version-branches.yml@v1
