name: CD

on:
  release:
    types:
      - prereleased
      - released

jobs:
  milestone:
    if: startsWith(github.ref, 'refs/tags')
    uses: ComPWA/actions/.github/workflows/close-milestone.yml@24413cd08a4657e18a344713ff7e91360dff9b0d # v4.1.0
  push:
    if: startsWith(github.ref, 'refs/tags') && !github.event.release.prerelease
    secrets: inherit
    uses: ComPWA/actions/.github/workflows/push-to-version-branches.yml@24413cd08a4657e18a344713ff7e91360dff9b0d # v4.1.0
