# cspell:ignore unittests

name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  style:
    name: Style checks
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r reqs/3.7/requirements-sty.txt
          pip install .
          sudo npm install -g pyright
      - name: Perform style checks
        run: pre-commit run -a
      - name: Run pyright
        run: pyright
