name: CI

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  PYTHONHASHSEED: "0"

on:
  push:
    branches:
      - main
      - epic/*
  pull_request:
    branches:
      - main
      - epic/*
  workflow_dispatch:

jobs:
  pytest:
    uses: ComPWA/actions/.github/workflows/pytest.yml@dev
    with:
      coverage-target: repo_maintenance
      macos-python-version: "3.7"
  style:
    uses: ComPWA/actions/.github/workflows/pre-commit.yml@dev
