name: CI

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  PYTHONHASHSEED: "0"

on:
  push:
    branches:
      - main
      - epic/*
  pull_request:
    branches:
      - main
      - epic/*
  workflow_dispatch:
    inputs:
      specific-pip-packages:
        description: Run CI with specific pip packages
        required: false
        type: string

jobs:
  pytest:
    uses: ComPWA/actions/.github/workflows/pytest.yml@v1
    with:
      coverage-target: repoma
      macos-python-version: "3.7"
      specific-pip-packages: ${{ inputs.specific-pip-packages }}
  style:
    if: inputs.specific-pip-packages == ''
    secrets: inherit
    uses: ComPWA/actions/.github/workflows/pre-commit.yml@v1
