name: Clean cache

on:
  pull_request:
    types:
      - closed
  workflow_dispatch:

jobs:
  cleanup:
    name: Remove PR caches
    runs-on: ubuntu-22.04
    steps:
      - uses: ComPWA/actions/clean-caches@v1
