name: Clean caches

on:
  pull_request:
    types:
      - closed
  workflow_dispatch:
    inputs:
      ref:
        description: Clean caches for this branch name or ref
        required: false
        type: string

jobs:
  cleanup:
    name: Remove caches
    runs-on: ubuntu-slim
    steps:
      - uses: ComPWA/actions/clean-caches@e72eb52f3e2af05d94b83d4f66330ce89f87314c # PR 182
        with:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ref: ${{ inputs.ref }}
