name: PR linting
on:
  pull_request:
    types:
      - edited
      - labeled
      - opened
      - reopened
      - synchronize
      - unlabeled

jobs:
  lint-pr:
    uses: ComPWA/actions/.github/workflows/pr-linting.yml@99e91bcc486218c7dbbb4f2e0319bfcb028562aa # 4.0.1
