name: PR linting
on:
  pull_request:
    types:
      - edited
      - labeled
      - opened
      - reopened
      - synchronize
      - unlabeled

jobs:
  lint-pr:
    uses: ComPWA/actions/.github/workflows/pr-linting.yml@9ccbc279d7813fb8ceca8d3b1cda27e584695ab9 # PR 183
