name: PR linting
on:
  pull_request:
    types:
      - edited
      - labeled
      - opened
      - reopened
      - synchronize
      - unlabeled

jobs:
  lint-pr:
    uses: ComPWA/actions/.github/workflows/pr-linting.yml@24413cd08a4657e18a344713ff7e91360dff9b0d # v4.1.0
