# cspell:disable
name: Labels

on:
  workflow_dispatch:

jobs:
  style:
    name: Sync labels
    runs-on: ubuntu-24.04
    env:
      LABELS_USERNAME: "${{ secrets.LABELS_USERNAME }}"
      LABELS_TOKEN: "${{ secrets.LABELS_TOKEN }}"
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install labels
      - name: Sync general issue labels
        run: |
          labels sync --filename labels/default.toml --owner ComPWA --repo actions
          labels sync --filename labels/default.toml --owner ComPWA --repo ampform
          labels sync --filename labels/default.toml --owner ComPWA --repo ampform-dpd
          labels sync --filename labels/default.toml --owner ComPWA --repo benchmarks
          labels sync --filename labels/default.toml --owner ComPWA --repo compwa.github.io
          labels sync --filename labels/default.toml --owner ComPWA --repo demo
          labels sync --filename labels/default.toml --owner ComPWA --repo jax-mini-benchmark
          labels sync --filename labels/default.toml --owner ComPWA --repo policy
          labels sync --filename labels/default.toml --owner ComPWA --repo prettier-pre-commit
          labels sync --filename labels/default.toml --owner ComPWA --repo pyright-pre-commit
          labels sync --filename labels/default.toml --owner ComPWA --repo qrules
          labels sync --filename labels/default.toml --owner ComPWA --repo sphinx-api-relink
          labels sync --filename labels/default.toml --owner ComPWA --repo sphinx-hep-pdgref
          labels sync --filename labels/default.toml --owner ComPWA --repo sphinx-pybtex-etal-style
          labels sync --filename labels/default.toml --owner ComPWA --repo sphinxcontrib-hep-pdgref
          labels sync --filename labels/default.toml --owner ComPWA --repo taplo-pre-commit
          labels sync --filename labels/default.toml --owner ComPWA --repo tensorwaves
          labels sync --filename labels/default.toml --owner ComPWA --repo update-pip-constraints
          labels sync --filename labels/default.toml --owner ComPWA --repo update-pre-commit

      - name: Sync issue labels for physics repositories
        run: |
          labels sync --filename labels/physics.toml --owner ComPWA --repo .github
          labels sync --filename labels/physics.toml --owner ComPWA --repo .github-private
          labels sync --filename labels/physics.toml --owner ComPWA --repo gluex-amplitude
          labels sync --filename labels/physics.toml --owner ComPWA --repo gluex-nstar
          labels sync --filename labels/physics.toml --owner ComPWA --repo gluex-nstar-analysis
          labels sync --filename labels/physics.toml --owner ComPWA --repo K-matrix-research
          labels sync --filename labels/physics.toml --owner ComPWA --repo Nstar-docs
          labels sync --filename labels/physics.toml --owner ComPWA --repo polarimetry
          labels sync --filename labels/physics.toml --owner ComPWA --repo PWA-JPsi2pbarSigmaKS
          labels sync --filename labels/physics.toml --owner ComPWA --repo report
          labels sync --filename labels/physics.toml --owner ComPWA --repo strong2020-salamanca
          labels sync --filename labels/physics.toml --owner ComPWA --repo PWA-pages

      - name: Sync issue labels for meeting repository
        run: |
          labels sync --filename labels/meeting.toml --owner ComPWA --repo RUB-EP1-Fritsch
